signed_integer_type   = 'i8' | 'i16' | 'i32' | 'i64';
unsigned_integer_type = 'u8' | 'u16' | 'u32' | 'u64';
floating_point_type   = 'f32' | 'f64';

type = signed_integer_type | unsigned_integer_type | floating_point_type
     | 'string';

expression = ;
statement = ;

program = { statement ';' } (* the empty program is also a valid program! *)